/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardPeriod: typeof import('./src/components/periods/CardPeriod.vue')['default']
    Cards: typeof import('./src/components/dashboard/Cards.vue')['default']
    CardsComponent: typeof import('./src/components/dashboard/CardsComponent.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    ChartComponent: typeof import('./src/components/dashboard/ChartComponent.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    FeaturesWidget: typeof import('./src/components/ui/landing/FeaturesWidget.vue')['default']
    HeroWidget: typeof import('./src/components/ui/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/ui/landing/HighlightsWidget.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Panel: typeof import('primevue/panel')['default']
    PanelComponent: typeof import('./src/components/dashboard/PanelComponent.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RecordsComponent: typeof import('./src/components/records/RecordsComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Slider: typeof import('primevue/slider')['default']
    TableComponent: typeof import('./src/components/dashboard/TableComponent.vue')['default']
    TableGroupComponent: typeof import('./src/components/groups/TableGroupComponent.vue')['default']
    TableQualifications: typeof import('./src/components/qualifications/TableQualifications.vue')['default']
    TableStudentComponent: typeof import('./src/components/students/TableStudentComponent.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    TopbarWidget: typeof import('./src/components/ui/landing/TopbarWidget.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
